export const ROUTES = {
  HOME: '/',
  LANGUAGES: '/languages',
  LANGUAGE_DETAIL: (slug: string) => `/languages/${slug}`,
  DEMO: '/demo',
  RESEARCH: '/research',
  RESEARCH_PAPERS: '/research/papers',
  RESEARCH_PAPER_DETAIL: (slug: string) => `/research/papers/${slug}`,
  RESEARCH_DATASETS: '/research/datasets',
  RESEARCH_BENCHMARKS: '/research/benchmarks',
  CONTRIBUTE: '/contribute',
  CONTRIBUTE_RECORD: '/contribute/record',
  CONTRIBUTE_TRANSLATE: '/contribute/translate',
  CONTRIBUTE_VALIDATE: '/contribute/validate',
  COMMUNITY: '/community',
  COMMUNITY_MEMBERS: '/community/members',
  COMMUNITY_EVENTS: '/community/events',
  BLOG: '/blog',
  BLOG_POST: (slug: string) => `/blog/${slug}`,
  BLOG_CATEGORY: (slug: string) => `/blog/category/${slug}`,
  ABOUT: '/about',
  CONTACT: '/contact',
} as const;

